/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SuntechRouteImport } from './routes/suntech'
import { Route as MdRouteImport } from './routes/md'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as InfotechRouteImport } from './routes/infotech'
import { Route as FreshRouteImport } from './routes/fresh'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CeoRouteImport } from './routes/ceo'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SuntechRoute = SuntechRouteImport.update({
  id: '/suntech',
  path: '/suntech',
  getParentRoute: () => rootRouteImport,
} as any)
const MdRoute = MdRouteImport.update({
  id: '/md',
  path: '/md',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const InfotechRoute = InfotechRouteImport.update({
  id: '/infotech',
  path: '/infotech',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshRoute = FreshRouteImport.update({
  id: '/fresh',
  path: '/fresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoRoute = CeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ceo': typeof CeoRoute
  '/contact': typeof ContactRoute
  '/fresh': typeof FreshRoute
  '/infotech': typeof InfotechRoute
  '/leadership': typeof LeadershipRoute
  '/md': typeof MdRoute
  '/suntech': typeof SuntechRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ceo': typeof CeoRoute
  '/contact': typeof ContactRoute
  '/fresh': typeof FreshRoute
  '/infotech': typeof InfotechRoute
  '/leadership': typeof LeadershipRoute
  '/md': typeof MdRoute
  '/suntech': typeof SuntechRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ceo': typeof CeoRoute
  '/contact': typeof ContactRoute
  '/fresh': typeof FreshRoute
  '/infotech': typeof InfotechRoute
  '/leadership': typeof LeadershipRoute
  '/md': typeof MdRoute
  '/suntech': typeof SuntechRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ceo'
    | '/contact'
    | '/fresh'
    | '/infotech'
    | '/leadership'
    | '/md'
    | '/suntech'
    | '/sustainability'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ceo'
    | '/contact'
    | '/fresh'
    | '/infotech'
    | '/leadership'
    | '/md'
    | '/suntech'
    | '/sustainability'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ceo'
    | '/contact'
    | '/fresh'
    | '/infotech'
    | '/leadership'
    | '/md'
    | '/suntech'
    | '/sustainability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CeoRoute: typeof CeoRoute
  ContactRoute: typeof ContactRoute
  FreshRoute: typeof FreshRoute
  InfotechRoute: typeof InfotechRoute
  LeadershipRoute: typeof LeadershipRoute
  MdRoute: typeof MdRoute
  SuntechRoute: typeof SuntechRoute
  SustainabilityRoute: typeof SustainabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suntech': {
      id: '/suntech'
      path: '/suntech'
      fullPath: '/suntech'
      preLoaderRoute: typeof SuntechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/md': {
      id: '/md'
      path: '/md'
      fullPath: '/md'
      preLoaderRoute: typeof MdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infotech': {
      id: '/infotech'
      path: '/infotech'
      fullPath: '/infotech'
      preLoaderRoute: typeof InfotechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fresh': {
      id: '/fresh'
      path: '/fresh'
      fullPath: '/fresh'
      preLoaderRoute: typeof FreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo': {
      id: '/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof CeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CeoRoute: CeoRoute,
  ContactRoute: ContactRoute,
  FreshRoute: FreshRoute,
  InfotechRoute: InfotechRoute,
  LeadershipRoute: LeadershipRoute,
  MdRoute: MdRoute,
  SuntechRoute: SuntechRoute,
  SustainabilityRoute: SustainabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
